[features]
seeds = false
[programs.localnet]
platform = "9LhUyaj7hcpBMZVrigHUyrsq5tysdD47NgEzsXB9Nt4z"
farm = "6mMVWS9wvoME4hg3DdytZGVMQT7f6hX2KKPQMRMhe7iv"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/adilcpm/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
